"""Structured logging — JSON machine-readable + Markdown human-readable."""

import json
from datetime import datetime, timezone
from pathlib import Path


class SessionLogger:
    """Logs every turn to JSON and produces a session report."""

    def __init__(self, session_id: str | None = None):
        self.session_id = session_id or datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
        self.start_time = datetime.now(timezone.utc)
        self.logs_dir = Path("logs")
        self.logs_dir.mkdir(exist_ok=True)
        self.log_file = self.logs_dir / f"session-{self.session_id}.jsonl"
        self.turns: list[dict] = []
        self.task_results: list[dict] = []

    def log_turn(
        self,
        task_id: str,
        turn: int,
        agent: str,
        input_tokens: int,
        output_tokens: int,
        cost_usd: float,
        response_type: str,
        detail: str | None = None,
    ) -> None:
        """Log a single turn to JSONL file and in-memory list."""
        entry = {
            "task_id": task_id,
            "turn": turn,
            "agent": agent,
            "input_tokens": input_tokens,
            "output_tokens": output_tokens,
            "cost_usd": round(cost_usd, 6),
            "response_type": response_type,
            "detail": detail[:500] if detail else None,
            "timestamp": datetime.now(timezone.utc).isoformat(),
        }

        self.turns.append(entry)

        with open(self.log_file, "a") as f:
            f.write(json.dumps(entry) + "\n")

    def record_task_result(self, result: dict) -> None:
        """Record a completed task result for the session report."""
        self.task_results.append(result)

    def write_report(self) -> str:
        """Write session report to reports/ directory.

        Returns:
            Path to the written report file.
        """
        reports_dir = Path("reports")
        reports_dir.mkdir(exist_ok=True)
        report_path = reports_dir / f"session-{self.session_id}.md"

        end_time = datetime.now(timezone.utc)
        elapsed = end_time - self.start_time

        total_tokens = sum(t["input_tokens"] + t["output_tokens"] for t in self.turns)
        total_cost = sum(t["cost_usd"] for t in self.turns)

        completed = [r for r in self.task_results if r.get("status") == "complete"]
        blocked = [r for r in self.task_results if r.get("status") == "blocked"]
        failed = [r for r in self.task_results if r.get("status") == "failed"]

        lines = [
            f"# Spectricom Orchestrator — Session Report",
            f"",
            f"**Session ID:** {self.session_id}",
            f"**Started:** {self.start_time.isoformat()}",
            f"**Ended:** {end_time.isoformat()}",
            f"**Elapsed:** {elapsed}",
            f"",
            f"## Summary",
            f"",
            f"| Metric | Value |",
            f"|--------|-------|",
            f"| Tasks completed | {len(completed)} |",
            f"| Tasks blocked | {len(blocked)} |",
            f"| Tasks failed | {len(failed)} |",
            f"| Total tokens | {total_tokens:,} |",
            f"| Total cost (est.) | ${total_cost:.4f} |",
            f"| Total turns | {len(self.turns)} |",
            f"",
        ]

        if completed:
            lines.append("## Completed Tasks\n")
            for r in completed:
                lines.append(f"- **{r.get("task_id", "unknown")}**: {r.get('output', 'done')[:100]}")
                lines.append(f"  - Turns: {r['turns_used']}, Tokens: {r['total_tokens']:,}, Cost: ${r['cost_estimate']:.4f}")
            lines.append("")

        if blocked:
            lines.append("## Blocked Tasks (George: resolve these)\n")
            for r in blocked:
                lines.append(f"- **{r.get("task_id", "unknown")}**: {r.get('output', 'unknown reason')[:200]}")
                lines.append(f"  - Turns: {r['turns_used']}, Tokens: {r['total_tokens']:,}")
            lines.append("")

        if failed:
            lines.append("## Failed Tasks\n")
            for r in failed:
                lines.append(f"- **{r.get('task_id', 'unknown')}**: {r.get('output', 'unknown error')[:200]}")
            lines.append("")

        # Output files
        output_dir = Path("output")
        if output_dir.exists():
            output_files = list(output_dir.rglob("*"))
            output_files = [f for f in output_files if f.is_file()]
            if output_files:
                lines.append("## Output Files Written\n")
                for f in sorted(output_files):
                    lines.append(f"- `{f}`")
                lines.append("")

        lines.append("## JSON Log\n")
        lines.append(f"Full machine-readable log: `{self.log_file}`\n")
        lines.append("---\n")
        lines.append("*Generated by Spectricom Multi-Agent Orchestrator*\n")

        report_path.write_text("\n".join(lines))
        return str(report_path)
